# This workflow will compile the project, run the unit and integration tests

name: Run all tests

on:
  workflow_dispatch:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "30 6,12 * * 1-5"

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with Maven
        run: mvn verify

      - name: Analyse and upload Sonar report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn sonar:sonar 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.organization=chelxb 
          -Dsonar.projectKey=Chelxb_fizz-buzz-ws 
          -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
